name: Prettier for JS/TypeScript Code

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Cloning the repository
        uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - name: Check the JS/TypeScript Code Formatting
        uses: jsoref/prettier_action@composite
        with:
          prettier_options: '--check **/*.{ts,css,html,scss,json}'
